import { StyleSheet } from 'react-native';

export const ItemModalStyles = StyleSheet.create({
  modal: {
    margin: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modalContainer: {
    minWidth: '98%',
    minHeight: '70%',
    backgroundColor: 'white',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    position: 'relative',
    bottom: 0,
  },
  image: {
    width: '100%',
    aspectRatio: 12 / 16,
    height: 400,
    alignSelf: 'center',
  },
  cross: {
    position: 'absolute',
    right: 10,
    top: 10,
    paddingBottom: -5,
    borderRadius: 15,
    width: 35,
    height: 35,
    zIndex: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000090',
  },
  crossText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 22,
  },
  categoryText: {
    position: 'absolute',
    backgroundColor: '#00000090',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    right: 20,
    bottom: 20,
    color: 'white',
  },
  firstLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    alignItems: 'center',
    marginVertical: 10,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    width: '70%',
  },
  price: {
    fontSize: 16,
    fontWeight: '700',
  },
  rate: {
    position: 'absolute',
    backgroundColor: '#00000090',
    paddingHorizontal: 15,
    fontWeight: '600',
    paddingVertical: 5,
    borderRadius: 10,
    left: 20,
    bottom: 20,
    color: 'white',
  },
  description: {
    marginTop: 15,
    marginBottom: 25,
    paddingHorizontal: 15,
    fontSize: 14,
    fontWeight: '500',
  },
});
